name: Format
on: [push]
jobs:
  format:
    runs-on: bamboo
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: yarn install
      - run: yarn run fix
      - run: yarn run doc:generate
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
