name: Node.js Package

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: bamboo
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: yarn install
      - run: yarn test:ci

  publish-gpr:
    needs: build
    runs-on: bamboo
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: https://npm.pkg.github.com/
      - run: yarn ci
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
